POST http://127.0.0.1:8000/login
Content-Type: application/json

{"username":"roba", "password": "123"}

###


POST http://127.0.0.1:8000/signup
Content-Type: application/json

{"username":"rbi", "password": "123", "email":"lol@mail.zxc"}

###

GET http://127.0.0.1:8000/test_token
Content-Type: application/json
Authorization: Token 7ecfb6d7e79df69c34d448d17a92151211498ba

{}

###