# Generated by Django 5.0.6 on 2024-05-13 17:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_group_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='created',
            field=models.DateField(verbose_name=datetime.datetime(2024, 5, 13, 17, 54, 22, 872366, tzinfo=datetime.timezone.utc)),
        ),
    ]
