# Generated by Django 5.0.6 on 2024-05-15 19:39

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_debt_user_owner_alter_group_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='debt_participants',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='group',
            name='debt_counter',
            field=models.TextField(default='{}'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='rem_counter',
            field=models.TextField(default='{}'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='debt',
            name='user_owner',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='group',
            name='created',
            field=models.DateField(default=datetime.datetime(2024, 5, 15, 19, 38, 46, 965083, tzinfo=datetime.timezone.utc)),
        ),
    ]
