# Generated by Django 5.0.6 on 2024-05-09 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('debt', models.BooleanField()),
                ('groups', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='api.group')),
            ],
        ),
    ]
