# Generated by Django 5.0.6 on 2024-05-12 10:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_group_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='created',
            field=models.DateField(default='1111-11-11', verbose_name=datetime.datetime(2024, 5, 12, 10, 12, 1, 780473, tzinfo=datetime.timezone.utc)),
        ),
    ]
