# Generated by Django 5.0.6 on 2024-05-11 16:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_group_created_alter_user_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='created',
            field=models.DateField(default='1111-11-11', verbose_name=datetime.datetime(2024, 5, 11, 16, 16, 10, 356364, tzinfo=datetime.timezone.utc)),
        ),
    ]
