# Generated by Django 5.0.6 on 2024-05-14 10:25

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_group_created_alter_group_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debt',
            name='user_owner',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='group',
            name='created',
            field=models.DateField(default=datetime.datetime(2024, 5, 14, 10, 25, 42, 38616, tzinfo=datetime.timezone.utc)),
        ),
    ]
