# Generated by Django 5.0.6 on 2024-05-12 16:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_group_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='kek@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='group',
            name='created',
            field=models.DateField(default='1111-11-11', verbose_name=datetime.datetime(2024, 5, 12, 16, 51, 26, 980398, tzinfo=datetime.timezone.utc)),
        ),
    ]
