# Generated by Django 5.0.6 on 2024-05-12 19:19

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_group_created_alter_group_debts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='debt',
        ),
        migrations.AddField(
            model_name='debt',
            name='user_owner',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='owns',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='group',
            name='created',
            field=models.DateField(default='1111-11-11', verbose_name=datetime.datetime(2024, 5, 12, 19, 19, 33, 183606, tzinfo=datetime.timezone.utc)),
        ),
        migrations.RemoveField(
            model_name='group',
            name='debts',
        ),
        migrations.AddField(
            model_name='group',
            name='debts',
            field=models.ManyToManyField(to='api.debt'),
        ),
    ]
