# Generated by Django 5.0.6 on 2024-05-12 19:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_user_debt_debt_user_owner_user_owns_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='created',
            field=models.DateField(default='1111-11-11', verbose_name=datetime.datetime(2024, 5, 12, 19, 25, 19, 970369, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='owns',
            field=models.BooleanField(default=False),
        ),
    ]
