# Generated by Django 5.0.6 on 2024-05-12 23:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_group_created_alter_user_owns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='created',
            field=models.DateField(default='1111-11-11', verbose_name=datetime.datetime(2024, 5, 12, 23, 45, 38, 648485, tzinfo=datetime.timezone.utc)),
        ),
    ]
