# Generated by Django 5.0.6 on 2024-05-12 23:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_group_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='debt',
            old_name='debts',
            new_name='debts_amounts',
        ),
        migrations.AlterField(
            model_name='group',
            name='created',
            field=models.DateField(default='1111-11-11', verbose_name=datetime.datetime(2024, 5, 12, 23, 49, 3, 464280, tzinfo=datetime.timezone.utc)),
        ),
    ]
