# Generated by Django 5.0.6 on 2024-05-13 14:14

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_debt_user_owner_alter_group_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debt',
            name='user_owner',
            field=models.ForeignKey(choices=[('value1', 'Label 1'), ('value2', 'Label 2')], default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='group',
            name='created',
            field=models.DateField(default='1111-11-11', verbose_name=datetime.datetime(2024, 5, 13, 14, 14, 42, 338311, tzinfo=datetime.timezone.utc)),
        ),
    ]
