# Generated by Django 5.0.4 on 2024-05-30 11:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payback", "0002_usergroup"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="usergroup",
            unique_together={("user", "group")},
        ),
    ]
