# Generated by Django 5.0.4 on 2024-06-01 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payback", "0004_userprofile"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="userprofile",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="iban",
            field=models.CharField(blank=True, max_length=34, null=True),
        ),
    ]
