# Generated by Django 5.0.4 on 2024-06-01 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payback", "0006_membership_group_members"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="membership",
            unique_together=set(),
        ),
    ]
