# Generated by Django 5.0.4 on 2024-06-18 09:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payback", "0011_friends"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="date_of_registration",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
