# Generated by Django 5.0.6 on 2024-07-17 14:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payback', '0012_expense_date_of_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='owes',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 17, 14, 53, 50, 370756, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='owes',
            name='last_notification_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 17, 14, 53, 50, 370756, tzinfo=datetime.timezone.utc)),
        ),
    ]
