# Generated by Django 5.0.6 on 2024-07-13 19:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payback', '0012_expense_date_of_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='owes',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 13, 19, 35, 27, 370188, tzinfo=datetime.timezone.utc)),
        ),
    ]
