# Generated by Django 5.0.6 on 2024-07-18 15:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payback', '0013_owes_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='owes',
            name='last_notification_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 18, 15, 50, 53, 826666, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='owes',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 18, 15, 50, 53, 826666, tzinfo=datetime.timezone.utc)),
        ),
    ]
