# Generated by Django 5.0.4 on 2024-07-18 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payback", "0013_owes_date"),
        ("payback", "0013_owes_date_owes_last_notification_date"),
    ]

    operations = []
