# Generated by Django 5.0.6 on 2024-07-13 19:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payback', '0013_owes_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owes',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 13, 19, 39, 54, 812356, tzinfo=datetime.timezone.utc)),
        ),
    ]
