# Generated by Django 5.0.6 on 2024-07-18 15:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payback', '0014_owes_last_notification_date_alter_owes_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owes',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 18, 15, 51, 54, 518501, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='owes',
            name='last_notification_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 18, 15, 51, 54, 518501, tzinfo=datetime.timezone.utc)),
        ),
    ]
