# Generated by Django 5.0.6 on 2024-07-15 09:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payback', '0015_alter_owes_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owes',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 15, 9, 48, 15, 787228, tzinfo=datetime.timezone.utc)),
        ),
    ]
