# Generated by Django 5.0.6 on 2024-07-16 15:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payback', '0016_alter_owes_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owes',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 16, 15, 38, 35, 235290, tzinfo=datetime.timezone.utc)),
        ),
    ]
